# Generated by Django 4.2.6 on 2023-10-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='fp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tp',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField()),
                ('win', models.IntegerField()),
                ('fp', models.IntegerField()),
                ('pp', models.IntegerField()),
                ('tp', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgis.team')),
            ],
        ),
    ]
